from .advisor import admin as advisor_admin 
from .batch import admin as batch_admin
from .category import admin as category_admin
from .member import admin as member_admin
from .note import admin as note_admin
from .phase import admin as phase_admin 
from .priority import admin as priority_admin
from .role import admin as role_admin
from .startup import admin as startup_admin
from .status import admin as status_admin