# Generated by Django 5.0.2 on 2024-10-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='email',
        ),
    ]
