# Generated by Django 5.0.2 on 2024-10-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_batch_category_founder_startup_delete_starup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='startups', to='startup.category'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founders',
            field=models.ManyToManyField(blank=True, null=True, related_name='startups', to='startup.founder'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='phase',
            field=models.CharField(blank=True, choices=[('brainstorming', 'Brainstorming'), ('fundraising', 'Fundraising'), ('scaling', 'Scaling'), ('established', 'Established')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitchdecks/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
