# Generated by Django 5.0.2 on 2024-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_batch_category_founder_startup_delete_starup'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='shorthand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
