# Generated by Django 5.0.2 on 2024-10-25 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_category_founder_startup_delete_starup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='founder',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='startup.batch'),
        ),
    ]
