# Generated by Django 5.0.2 on 2024-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_alter_startup_categories_alter_startup_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='phase',
            field=models.CharField(blank=True, choices=[('brainstorming', 'Brainstorming'), ('fundraising', 'Fundraising'), ('scaling', 'Scaling'), ('established', 'Established')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
