# Generated by Django 5.0.2 on 2024-10-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_batch_alter_founder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='startup.batch'),
        ),
    ]
