# Generated by Django 5.0.2 on 2024-10-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_startup_priority_alter_startup_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
