# Generated by Django 5.0.2 on 2024-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_alter_founder_shorthand'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
