# Generated by Django 5.0.2 on 2024-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_startup_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
