# Generated by Django 5.0.2 on 2024-10-27 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_alter_startup_avatar_alter_startup_pitch_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='avatar/')),
            ],
        ),
        migrations.AlterField(
            model_name='startup',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='startup.avatar'),
        ),
    ]
