# Generated by Django 5.0.2 on 2024-10-27 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_avatar_alter_startup_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitchdeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitchdeck', models.FileField(upload_to='pitchdecks/')),
                ('name', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='startup.pitchdeck'),
        ),
    ]
