# Generated by Django 5.0.2 on 2024-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
