# Generated by Django 5.0.2 on 2024-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Pitchdeck',
        ),
    ]
