# Generated by Django 5.0.2 on 2024-12-07 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='core.category'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='phases',
            field=models.ManyToManyField(blank=True, null=True, related_name='startups', to='core.phase'),
        ),
    ]
