# Generated by Django 5.0.2 on 2024-12-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_startup_category_alter_startup_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='launch_date',
        ),
    ]
